made necessary changes to integrate embunit test suite into clydefs and wrote an initial set of tests exercising the io module's create_tree,remove_tree and insert_node commands

diff --git a/fs/clydefs/Makefile b/fs/clydefs/Makefile
--- a/fs/clydefs/Makefile
+++ b/fs/clydefs/Makefile
@@ -1,3 +1,55 @@
-obj-$(CONFIG_CLYDEFS_CORE_FS) := clydefs.o
+KMAK_FLAGS := \
+	CONFIG_CLYDEFS_CORE_FS=m \
+	KDIR=${KDIR}
 
-clydefs-y += super.o file.o inode.o io.o
+ifneq ($(KERNELRELEASE),)
+	EMBUNIT_DIR := ../../embunit
+	EMBUNIT_SRC := $(EMBUNIT_DIR)/embUnit
+	EMBUNIT_SAMPLES := $(EMBUNIT_DIR)/samples
+
+	ccflags-y += -I$(src)/$(EMBUNIT_DIR)
+	ccflags-y += -I$(src)/$(EMBUNIT_DIR)/wrap
+	ccflags-y += -DNO_STDIO_PRINTF
+	
+	obj-$(CONFIG_CLYDEFS_FS) := clydefs.o
+	
+	clydefs-y += init.o super.o file.o inode.o io.o
+
+	#debugging build
+	ifneq ($(CONFIG_CLYDEFS_DEBUG),)
+		#test code
+		clydefs-y += test.o testio.o
+		
+		#embunit
+		clydefs-y += $(EMBUNIT_SRC)/AssertImpl.o
+		clydefs-y += $(EMBUNIT_SRC)/RepeatedTest.o
+		clydefs-y += $(EMBUNIT_SRC)/stdImpl.o
+		clydefs-y += $(EMBUNIT_SRC)/TestCaller.o
+		clydefs-y += $(EMBUNIT_SRC)/TestCase.o
+		clydefs-y += $(EMBUNIT_SRC)/TestResult.o
+		clydefs-y += $(EMBUNIT_SRC)/TestRunner.o
+		clydefs-y += $(EMBUNIT_SRC)/TestSuite.o
+	endif
+# out of kernel build
+else
+	KDIR ?= /lib/modules/$(shell uname -r)/build
+	PWD := $(shell pwd)
+
+
+default: prep
+	echo "making clydefs..."
+	$(MAKE) -C "$(KDIR)" M="$(PWD)" $(KMAK_FLAGS) modules
+
+prep:
+	@test -r "$(KDIR)/.config" || { \
+		echo "error: $(KDIR) sources are not configured." 1>&2; \
+		false; \
+	}
+	@test -r "$(KDIR)/include/asm-generic" || { \
+		echo "error: $(KDIR) sources are not prepared." 1>&2; \
+		false; \
+	}
+
+clean:
+	rm -rf *.o *.ko *.mod.c .tmp_versions .*.cmd modules.order
+endif
